services:
  web:
    container_name: scrapy-web
    build:
      context: .
      dockerfile: apps/frontend/web/Dockerfile
    image: scrapy-web
    ports:
      - "3001:3000"
    networks:
      - scrapynet
    depends_on:
      - auth

  auth:
    container_name: scrapy-auth
    build:
      context: .
      dockerfile: apps/backend/auth/Dockerfile
    image: scrapy-auth
    ports:
      - "3002:3001"
    env_file: apps/backend/auth/.env
    networks:
      - scrapynet
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: express_db
    volumes:
      - ./data/db:/var/lib/postgresql/data:z
    networks:
      - scrapynet
    ports:
      - "5432:5432"

  caddy:
    image: caddy:alpine
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:z
    networks:
      - scrapynet
    restart: unless-stopped

networks:
  scrapynet:
    external: true
