services:
  web:
    container_name: scrapy-web
    restart: unless-stopped
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    image: scrapy-web
    ports:
      - "3001:3000"
    networks:
      - scrapynet
    depends_on:
      - auth

  auth:
    container_name: scrapy-auth
    restart: unless-stopped
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
    image: scrapy-auth
    ports:
      - "3002:3001"
    env_file: apps/auth/.env
    networks:
      - scrapynet
    depends_on:
      - db

  migrate:
    container_name: scrapy-migrate
    build:
      context: .
      dockerfile: apps/auth/Dockerfile.migrate
    image: scrapy-migrate
    env_file: apps/auth/.env
    networks:
      - scrapynet
    depends_on:
      - db
    restart: "no"

  db:
    image: postgres:18.3
    container_name: postgres_db
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: express_db
    volumes:
      - ./data/db:/var/lib/postgresql/data:z
    networks:
      - scrapynet
    ports:
      - "5432:5432"

networks:
  scrapynet:
    external: true
