services:
  web:
    container_name: scrapy-web
    restart: unless-stopped
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    image: scrapy-web
    ports:
      - "3001:3000"
    networks:
      - scrapynet
    depends_on:
      - auth

  auth:
    container_name: scrapy-auth
    restart: unless-stopped
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
    image: scrapy-auth
    ports:
      - "3002:3001"
    env_file: apps/auth/.env
    networks:
      - scrapynet
    depends_on:
      - db

  migrate:
    container_name: scrapy-migrate
    build:
      context: .
      dockerfile: apps/auth/Dockerfile.migrate
    image: scrapy-migrate
    env_file: apps/auth/.env
    networks:
      - scrapynet
    depends_on:
      - db
    restart: "no"

  db:
    image: postgres:18.3
    container_name: postgres_db
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: express_db
    volumes:
      - ./data:/var/lib/postgresql:z
    networks:
      - scrapynet
    ports:
      - "5432:5432"

  fastapi:
    build:
      context: ./apps/backend
      dockerfile: apps/backend/Dockerfile
    image: scrapy-fastapi
    container_name: scrapy-fastapi
    environment:
      HOT_RELOAD: false
      QDRANT_ENDPOINT: http://qdrant:6333
      REDIS_HOST: redis
      REDIS_PORT: 6379
    env_file: .env
    ports:
      - 8081:8080
    networks:
      - scrapynet
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: src
          target: /app/src
        - action: rebuild
          path: ./pyproject.toml

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    networks:
      - scrapynet
    volumes:
      - ./qdrant_data:/qdrant/storage:z
    restart: unless-stopped

  redis:
    image: redis:8.2-alpine
    container_name: redis
    ports:
      - 6379:6379
    expose:
      - 6379
    networks:
      - scrapynet
    restart: unless-stopped

  redis-insight:
    image: redis/redisinsight:2.70
    container_name: redis-insight
    ports:
      - 5540:5540
    expose:
      - 5540
    environment:
      RI_REDIS_HOST: "redis"
    networks:
      - scrapynet
    restart: unless-stopped

configs:
  qdrant_config:
    content: |
      log_level: INFO

networks:
  scrapynet:
    external: true
