[project]
name = "scrapychat"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "fastapi[standard]>=0.119.0",
    "llama-index-embeddings-ollama>=0.8.4",
    "llama-index-llms-google-genai>=0.6.2",
    "llama-index-vector-stores-qdrant>=0.8.6",
    "playwright>=1.55.0",
    "pyrefly>=0.42.3",
    "python-jose>=3.5.0",
]

[tool.pyrefly]
project-includes = [
    "**/*.py*",
    "**/*.ipynb",
]
