FROM oven/bun:alpine AS base
WORKDIR /app

FROM base AS prepare
RUN bun add -g turbo
COPY . .
RUN turbo prune auth --docker

FROM base AS builder
COPY --from=prepare /app/out/json/ .
RUN bun install
COPY --from=prepare /app/out/full/ .

FROM base AS runner
COPY --from=builder /app .

WORKDIR /app/apps/auth
RUN bun install

CMD ["bun", "run", "migrate"]
